In [1]:
import pandas as pd
df = pd.read_pickle('../data/interim/aggregated.pkl')

In [2]:
import nltk
import string

#  Text Preprocessing

In [3]:
df['Contents']=df['Contents'].apply(lambda x: x if type(x)!=str else x.lower()) # lower case
df['Contents']=df['Contents'].apply(lambda x: ''.join([i for i in x
                                                                  if i not in string.punctuation]))
#df['Contents']=df['Contents'].apply(nltk.word_tokenize)

#stop = stopwords.words('english')


#df['Contents']=df['Contents'].apply(lambda x: ''.join([i for i in x 
#                                                       if i not in stop]))
df

,GUID,Date (GMT),URL,Contents,Author,Name,Country,State/Region,City/Urban Area,Category,Emotion,Source,Klout Score,Gender,Posts,Followers,Following
0,870067217320349696,31/05/2017 23:59,http://twitter.com/sharmilabousa/status/870067...,rudd goes in for a strong and stable photobomb...,@sharmilabousa,Sharmila_Bousa,United Kingdom,South West,Bristol,NaN,NaN,Twitter,NaN,F,44722.0,1421.0,1212.0
1,870067267488362496,31/05/2017 23:59,http://twitter.com/deadpubs/status/87006726748...,rt gareth13479 amberruddhr gets the prize for ...,@deadpubs,Pub History,United Kingdom,Greater London,London,NaN,NaN,Twitter,45.0,NaN,8595.0,296.0,21.0
2,870067179135397888,31/05/2017 23:59,http://twitter.com/IsThisAB0t/status/870067179...,rt tasminasheikh team thesnp auchterarder off ...,@IsThisAB0t,NOTBOT,United Kingdom,NaN,NaN,NaN,NaN,Twitter,61.0,NaN,364322.0,2269.0,1267.0
3,870067264099409921,31/05/2017 23:59,http://twitter.com/MsJoNeary/status/8700672640...,larmysausage hackneyabbott juliahb1 amberruddh...,@MsJoNeary,Joanna Neary,United Kingdom,NaN,NaN,NaN,NaN,Twitter,51.0,F,5193.0,1944.0,630.0
4,870067217085472768,31/05/2017 23:59,http://twitter.com/RoxethMyLord/status/8700672...,rt barbpitruz tulipsiddiq brilliant as always ...,@RoxethMyLord,Roxeth A.K.A.,United Kingdom,NaN,NaN,NaN,NaN,Twitter,43.0,NaN,29989.0,616.0,1647.0
5,870067355140984833,31/05/2017 23:59,http://twitter.com/king_darran/status/87006735...,andrewj2009 no joke no one is here to support...,@king_darran,Del thelink,United Kingdom,Greater London,London,NaN,NaN,Twitter,47.0,NaN,19330.0,1759.0,4999.0
6,870067213486706688,31/05/2017 23:59,http://twitter.com/AliMalik1x/status/870067213...,rt hackneyabbott in tough brexit negotiations ...,@AliMalik1x,That Halal Talk,United Kingdom,Greater London,London,NaN,NaN,Twitter,26.0,NaN,14092.0,389.0,217.0
7,870067159547949057,31/05/2017 23:59,http://twitter.com/Elin012/status/870067159547...,rt hackneyabbott in tough brexit negotiations ...,@Elin012,Elin Owen,United Kingdom,NaN,NaN,NaN,NaN,Twitter,40.0,NaN,31303.0,335.0,641.0
8,870067239126519808,31/05/2017 23:59,http://twitter.com/CaMrAn_12/status/8700672391...,rt hackneyabbott amberruddhr heard you were as...,@CaMrAn_12,Camran Shahid,NaN,NaN,NaN,NaN,NaN,Twitter,23.0,NaN,1906.0,64.0,104.0
9,870067357514911748,31/05/2017 23:59,http://twitter.com/AFILLEMON/status/8700673575...,rt hackneyabbott in tough brexit negotiations ...,@AFILLEMON,FILLEMON AMUKOTO,Namibia,Khomas,Windhoek,NaN,NaN,Twitter,13.0,NaN,43.0,23.0,67.0
10,870067189847650304,31/05/2017 23:59,http://twitter.com/spaceman_jamie/status/87006...,yvettecoopermp nice one,@spaceman_jamie,jamie,United Kingdom,NaN,NaN,NaN,NaN,Twitter,35.0,F,3674.0,152.0,560.0
11,870067159845699584,31/05/2017 23:59,http://twitter.com/conniepaterson/status/87006...,rt joannaccherry glorious day for a team cherr...,@conniepaterson,connie paterson,NaN,NaN,NaN,NaN,NaN,Twitter,27.0,F,6239.0,61.0,26.0
12,870067176539029504,31/05/2017 23:59,http://twitter.com/IsThisAB0t/status/870067176...,rt joannaccherry the truth about foodbanks fro...,@IsThisAB0t,NOTBOT,United Kingdom,NaN,NaN,NaN,NaN,Twitter,61.0,NaN,364321.0,2269.0,1267.0
13,870067078987907073,31/05/2017 23:58,http://twitter.com/GimmzAngolano/status/870067...,rt hackneyabbott amberruddhr heard you were as...,@GimmzAngolano,Eddie Bravo,NaN,NaN,NaN,NaN,NaN,Twitter,30.0,M,244.0,193.0,198.0
14,870066997970837509,31/05/2017 23:58,http://twitter.com/tehard/status/8700669979708...,rt paulmasonnews in that debate carolinelucas ...,@tehard,Teresa Harding,United Kingdom,East,NaN,NaN,NaN,Twitter,30.0,F,12392.0,125.0,114.0
15,870066981994733568,31/05/2017 23:58,http://twitter.com/LeeB155/status/870066981994...,hackneyabbott amberruddhr you clearly missed t...,@LeeB155,Dorset Yellow,United Kingdom,NaN,NaN,NaN,NaN,Twitter,30.0,NaN,1042.0,42.0,94.0
16,870067004585254912,31/05/2017 23:58,http://twitter.com/funksoulHulk/status/8700670...,sunapology hackneyabbott abbott is labours bor...,@funksoulHulk,Chris Noble,United Kingdom,North East,Middlesbrough,NaN,NaN,Twitter,41.0,M,17171.0,322.0,565.0
17,870067031005179905,31/05/2017 23:58,http://twitter.com/MsJoNeary/status/8700670310...,stuh lachlanmoir hackneyabbott amberruddhr yes...,@MsJoNeary,Joanna Neary,United Kingdom,NaN,NaN,NaN,NaN,Twitter,51.0,F,5192.0,1944.0,630.0
18,870067074374266884,31/05/2017 23:58,http://twitter.com/A_mkn_/status/8700670743742...,rt hackneyabbott theresamay claims shes so tou...,@A_mkn_,AM,NaN,NaN,NaN,NaN,NaN,Twitter,28.0,NaN,10799.0,159.0,225.0
19,870066916689358848,31/05/2017 23:58,http://twitter.com/longlostlohan/status/870066...,rt hackneyabbott amberruddhr heard you were as...,@longlostlohan,full metal grandma,Malaysia,NaN,NaN,NaN,NaN,Twitter,28.0,NaN,58011.0,729.0,146.0
20,870067039930593284,31/05/2017 23:58,http://twitter.com/chunks_1892/status/87006703...,rt hackneyabbott amberruddhr heard you were as...,@chunks_1892,Richie McIvor,United Kingdom,North West,Liverpool,NaN,NaN,Twitter,26.0,M,3586.0,398.0,799.0
21,870066928559296513,31/05/2017 23:58,http://twitter.com/__lilyvictoria/status/87006...,rt hackneyabbott in tough brexit negotiations ...,@__lilyvictoria,lils,United Kingdom,NaN,NaN,NaN,NaN,Twitter,42.0,NaN,18808.0,884.0,1003.0
22,870067050500288512,31/05/2017 23:58,http://twitter.com/rhiannon_arian/status/87006...,rt sarahchampionmp did you notice rudd say cri...,@rhiannon_arian,Rhiannon Arian,NaN,NaN,NaN,NaN,NaN,Twitter,48.0,F,18602.0,624.0,343.0
23,870066869843177472,31/05/2017 23:58,http://twitter.com/janner_geek/status/87006686...,rt hackneyabbott in tough brexit negotiations ...,@janner_geek,Chris,United Kingdom,South West,Plymouth,NaN,NaN,Twitter,38.0,M,2424.0,164.0,351.0
24,870067101742116865,31/05/2017 23:58,http://twitter.com/T_G_Heathfield/status/87006...,rt hackneyabbott amberruddhr heard you were as...,@T_G_Heathfield,Thomas Heathfield,Spain,Madrid,Madrid,NaN,NaN,Twitter,13.0,M,88.0,29.0,59.0
25,870067112857001985,31/05/2017 23:58,http://twitter.com/conniepaterson/status/87006...,rt joannaccherry written questions are for bac...,@conniepaterson,connie paterson,NaN,NaN,NaN,NaN,NaN,Twitter,27.0,F,6238.0,61.0,26.0
26,870066712665784321,31/05/2017 23:57,http://twitter.com/TulipSiddiq/status/87006671...,rt lendunne i just had a conversation with tul...,@TulipSiddiq,Tulip Siddiq,United Kingdom,Greater London,London,NaN,NaN,Twitter,66.0,NaN,8947.0,34239.0,1091.0
27,870066756236304385,31/05/2017 23:57,http://twitter.com/louise1580/status/870066756...,paulinewoodhams hackneyabbott well thats not r...,@louise1580,Louise Gray,NaN,NaN,NaN,NaN,NaN,Twitter,40.0,F,565.0,74.0,210.0
28,870066699697102848,31/05/2017 23:57,http://twitter.com/JoePoePorter/status/8700666...,rt hackneyabbott in tough brexit negotiations ...,@JoePoePorter,Joseph Sama ??,United Kingdom,NaN,NaN,NaN,NaN,Twitter,33.0,M,30679.0,886.0,523.0
29,870066816453931008,31/05/2017 23:57,http://twitter.com/thomas_adf/status/870066816...,jessphillips pretty sexist judging a man on wh...,@thomas_adf,Thomas de Freitas,United Kingdom,NaN,NaN,NaN,NaN,Twitter,48.0,M,1985.0,192.0,474.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269970,817456021513928705,NaN,http://twitter.com/Princemezy/status/817456021...,httptwittercomprincemezystatus817456021513928705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,20.0,M,NaN,NaN,NaN
2269971,817467503978876930,NaN,http://twitter.com/NickThornber/status/8174675...,httptwittercomnickthornberstatus81746750397887...,NaN,NaN,United Kingdom,East Midlands,Leicester,NaN,NaN,Twitter,45.0,M,NaN,NaN,NaN
2269972,817410567082299392,NaN,http://twitter.com/LSanders_Star/status/817410...,httptwittercomlsandersstarstatus81741056708229...,NaN,NaN,United Kingdom,West Midlands,Birmingham,NaN,NaN,Twitter,48.0,F,NaN,NaN,NaN
2269973,817419881532555264,NaN,http://twitter.com/SimplyVeggie/status/8174198...,httptwittercomsimplyveggiestatus81741988153255...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,42.0,F,NaN,NaN,NaN
2269974,817280301676302336,NaN,http://twitter.com/AndrewGDavidson/status/8172...,httptwittercomandrewgdavidsonstatus81728030167...,NaN,NaN,United Kingdom,Greater London,London,NaN,NaN,Twitter,40.0,M,NaN,NaN,NaN
2269975,817509334313762817,NaN,http://twitter.com/peterhollely/status/8175093...,httptwittercompeterhollelystatus81750933431376...,NaN,NaN,United Kingdom,Greater London,London,NaN,NaN,Twitter,41.0,M,NaN,NaN,NaN
2269976,817176699481812993,NaN,http://twitter.com/billyboyRFC/status/81717669...,httptwittercombillyboyrfcstatus817176699481812993,NaN,NaN,United Kingdom,Northern Ireland,Belfast,NaN,NaN,Twitter,42.0,NaN,NaN,NaN,NaN
2269977,817442015680090113,NaN,http://twitter.com/godwin_nwaugo/status/817442...,httptwittercomgodwinnwaugostatus81744201568009...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,46.0,M,NaN,NaN,NaN
2269978,817311223985438720,NaN,http://twitter.com/iamths1973/status/817311223...,httptwittercomiamths1973status817311223985438720,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,50.0,M,NaN,NaN,NaN
2269979,817494230725787648,NaN,http://twitter.com/Gogofrancis/status/81749423...,httptwittercomgogofrancisstatus817494230725787648,NaN,NaN,Nigeria,Rivers,Port Harcourt,NaN,NaN,Twitter,34.0,M,NaN,NaN,NaN
2269980,817459744730480642,NaN,http://twitter.com/AP_Doramaqueen/status/81745...,httptwittercomapdoramaqueenstatus8174597447304...,NaN,NaN,United Kingdom,Greater London,London,NaN,NaN,Twitter,53.0,M,NaN,NaN,NaN
2269981,817378104305979392,NaN,http://twitter.com/markmcdsnp/status/817378104...,httptwittercommarkmcdsnpstatus817378104305979392,NaN,NaN,United Kingdom,North Eastern,Aberdeen,NaN,NaN,Twitter,64.0,M,NaN,NaN,NaN
2269982,817190780720807936,NaN,http://twitter.com/OsasSuly/status/81719078072...,httptwittercomosassulystatus817190780720807936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,18.0,NaN,NaN,NaN,NaN
2269983,817183165706096640,NaN,http://twitter.com/GMgbudom/status/81718316570...,httptwittercomgmgbudomstatus817183165706096640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,25.0,M,NaN,NaN,NaN
2269984,817334951184109568,NaN,http://twitter.com/shorerdloyal/status/8173349...,httptwittercomshorerdloyalstatus81733495118410...,NaN,NaN,United Kingdom,Northern Ireland,NaN,NaN,NaN,Twitter,39.0,NaN,NaN,NaN,NaN
2269985,817183085817188352,NaN,http://twitter.com/kamayoq/status/817183085817...,httptwittercomkamayoqstatus817183085817188352,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,25.0,NaN,NaN,NaN,NaN
2269986,817492736500760576,NaN,http://twitter.com/Osinachi01/status/817492736...,httptwittercomosinachi01status817492736500760576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,17.0,NaN,NaN,NaN,NaN
2269987,817310510655963137,NaN,http://twitter.com/CareIndustryNew/status/8173...,httptwittercomcareindustrynewstatus81731051065...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,46.0,NaN,NaN,NaN,NaN
2269988,817497684848349184,NaN,http://twitter.com/frackfreemps/status/8174976...,httptwittercomfrackfreempsstatus81749768484834...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,52.0,NaN,NaN,NaN,NaN
2269989,817360076759564288,NaN,http://twitter.com/NEWTEKWORLDNEWS/status/8173...,httptwittercomnewtekworldnewsstatus81736007675...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,NaN,NaN,NaN,NaN,NaN
2269990,817173445540794368,NaN,http://twitter.com/JohnMullenEdin/status/81717...,httptwittercomjohnmullenedinstatus817173445540...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,41.0,M,NaN,NaN,NaN
2269991,817478360578322433,NaN,http://twitter.com/SecureLegal/status/81747836...,httptwittercomsecurelegalstatus817478360578322433,NaN,NaN,United Kingdom,West Midlands,Stoke,NaN,NaN,Twitter,40.0,NaN,NaN,NaN,NaN
2269992,817295895888797696,NaN,http://twitter.com/ADPHUK/status/8172958958887...,httptwittercomadphukstatus817295895888797696,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,50.0,NaN,NaN,NaN,NaN
2269993,817377467606462464,NaN,http://twitter.com/misslucyp/status/8173774676...,httptwittercommisslucypstatus817377467606462464,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,45.0,F,NaN,NaN,NaN
2269994,817300618402533377,NaN,http://twitter.com/GMBCampaigns/status/8173006...,httptwittercomgmbcampaignsstatus81730061840253...,NaN,NaN,United Kingdom,East Midlands,NaN,NaN,NaN,Twitter,52.0,NaN,NaN,NaN,NaN
2269995,817511521093844992,NaN,http://twitter.com/Jamielog1/status/8175115210...,httptwittercomjamielog1status817511521093844992,NaN,NaN,United Kingdom,North West,Liverpool,NaN,NaN,Twitter,31.0,F,NaN,NaN,NaN
2269996,817312238197440513,NaN,http://twitter.com/AlisonJenner6/status/817312...,httptwittercomalisonjenner6status8173122381974...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,52.0,F,NaN,NaN,NaN
2269997,817412051991756800,NaN,http://twitter.com/LeeMartin113/status/8174120...,httptwittercomleemartin113status81741205199175...,NaN,NaN,United Kingdom,South Western,Greenock,NaN,NaN,Twitter,NaN,M,NaN,NaN,NaN
2269998,817460627312615424,NaN,http://twitter.com/msjanehenshaw/status/817460...,httptwittercommsjanehenshawstatus8174606273126...,NaN,NaN,United Kingdom,West Wales and the Valleys,Cardiff,NaN,NaN,Twitter,27.0,F,NaN,NaN,NaN
2269999,817436705431154688,NaN,http://twitter.com/JGJabbour/status/8174367054...,httptwittercomjgjabbourstatus817436705431154688,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,36.0,M,NaN,NaN,NaN

# Sentiment / Subjectivity Analysis

In [4]:
from textblob import TextBlob

def sentiment_calc(text):
    try:
        return TextBlob(text).sentiment
    except:
        return None
    
df['sentiment']=df['Contents'].apply(sentiment_calc)
df

,GUID,Date (GMT),URL,Contents,Author,Name,Country,State/Region,City/Urban Area,Category,Emotion,Source,Klout Score,Gender,Posts,Followers,Following,sentiment
0,870067217320349696,31/05/2017 23:59,http://twitter.com/sharmilabousa/status/870067...,rudd goes in for a strong and stable photobomb...,@sharmilabousa,Sharmila_Bousa,United Kingdom,South West,Bristol,NaN,NaN,Twitter,NaN,F,44722.0,1421.0,1212.0,"(0.4333333333333333, 0.7333333333333333)"
1,870067267488362496,31/05/2017 23:59,http://twitter.com/deadpubs/status/87006726748...,rt gareth13479 amberruddhr gets the prize for ...,@deadpubs,Pub History,United Kingdom,Greater London,London,NaN,NaN,Twitter,45.0,NaN,8595.0,296.0,21.0,"(0.3, 0.1)"
2,870067179135397888,31/05/2017 23:59,http://twitter.com/IsThisAB0t/status/870067179...,rt tasminasheikh team thesnp auchterarder off ...,@IsThisAB0t,NOTBOT,United Kingdom,NaN,NaN,NaN,NaN,Twitter,61.0,NaN,364322.0,2269.0,1267.0,"(0.0, 0.0)"
3,870067264099409921,31/05/2017 23:59,http://twitter.com/MsJoNeary/status/8700672640...,larmysausage hackneyabbott juliahb1 amberruddh...,@MsJoNeary,Joanna Neary,United Kingdom,NaN,NaN,NaN,NaN,Twitter,51.0,F,5193.0,1944.0,630.0,"(0.2857142857142857, 0.5357142857142857)"
4,870067217085472768,31/05/2017 23:59,http://twitter.com/RoxethMyLord/status/8700672...,rt barbpitruz tulipsiddiq brilliant as always ...,@RoxethMyLord,Roxeth A.K.A.,United Kingdom,NaN,NaN,NaN,NaN,Twitter,43.0,NaN,29989.0,616.0,1647.0,"(0.575, 0.6666666666666666)"
5,870067355140984833,31/05/2017 23:59,http://twitter.com/king_darran/status/87006735...,andrewj2009 no joke no one is here to support...,@king_darran,Del thelink,United Kingdom,Greater London,London,NaN,NaN,Twitter,47.0,NaN,19330.0,1759.0,4999.0,"(-0.2, 0.4)"
6,870067213486706688,31/05/2017 23:59,http://twitter.com/AliMalik1x/status/870067213...,rt hackneyabbott in tough brexit negotiations ...,@AliMalik1x,That Halal Talk,United Kingdom,Greater London,London,NaN,NaN,Twitter,26.0,NaN,14092.0,389.0,217.0,"(-0.3888888888888889, 0.8333333333333334)"
7,870067159547949057,31/05/2017 23:59,http://twitter.com/Elin012/status/870067159547...,rt hackneyabbott in tough brexit negotiations ...,@Elin012,Elin Owen,United Kingdom,NaN,NaN,NaN,NaN,Twitter,40.0,NaN,31303.0,335.0,641.0,"(-0.3888888888888889, 0.8333333333333334)"
8,870067239126519808,31/05/2017 23:59,http://twitter.com/CaMrAn_12/status/8700672391...,rt hackneyabbott amberruddhr heard you were as...,@CaMrAn_12,Camran Shahid,NaN,NaN,NaN,NaN,NaN,Twitter,23.0,NaN,1906.0,64.0,104.0,"(0.0, 0.18888888888888888)"
9,870067357514911748,31/05/2017 23:59,http://twitter.com/AFILLEMON/status/8700673575...,rt hackneyabbott in tough brexit negotiations ...,@AFILLEMON,FILLEMON AMUKOTO,Namibia,Khomas,Windhoek,NaN,NaN,Twitter,13.0,NaN,43.0,23.0,67.0,"(-0.3888888888888889, 0.8333333333333334)"
10,870067189847650304,31/05/2017 23:59,http://twitter.com/spaceman_jamie/status/87006...,yvettecoopermp nice one,@spaceman_jamie,jamie,United Kingdom,NaN,NaN,NaN,NaN,Twitter,35.0,F,3674.0,152.0,560.0,"(0.6, 1.0)"
11,870067159845699584,31/05/2017 23:59,http://twitter.com/conniepaterson/status/87006...,rt joannaccherry glorious day for a team cherr...,@conniepaterson,connie paterson,NaN,NaN,NaN,NaN,NaN,Twitter,27.0,F,6239.0,61.0,26.0,"(0.4, 0.9)"
12,870067176539029504,31/05/2017 23:59,http://twitter.com/IsThisAB0t/status/870067176...,rt joannaccherry the truth about foodbanks fro...,@IsThisAB0t,NOTBOT,United Kingdom,NaN,NaN,NaN,NaN,Twitter,61.0,NaN,364321.0,2269.0,1267.0,"(0.0, 0.0)"
13,870067078987907073,31/05/2017 23:58,http://twitter.com/GimmzAngolano/status/870067...,rt hackneyabbott amberruddhr heard you were as...,@GimmzAngolano,Eddie Bravo,NaN,NaN,NaN,NaN,NaN,Twitter,30.0,M,244.0,193.0,198.0,"(0.0, 0.18888888888888888)"
14,870066997970837509,31/05/2017 23:58,http://twitter.com/tehard/status/8700669979708...,rt paulmasonnews in that debate carolinelucas ...,@tehard,Teresa Harding,United Kingdom,East,NaN,NaN,NaN,Twitter,30.0,F,12392.0,125.0,114.0,"(0.05000000000000001, 0.19166666666666665)"
15,870066981994733568,31/05/2017 23:58,http://twitter.com/LeeB155/status/870066981994...,hackneyabbott amberruddhr you clearly missed t...,@LeeB155,Dorset Yellow,United Kingdom,NaN,NaN,NaN,NaN,Twitter,30.0,NaN,1042.0,42.0,94.0,"(-0.15, 0.5416666666666666)"
16,870067004585254912,31/05/2017 23:58,http://twitter.com/funksoulHulk/status/8700670...,sunapology hackneyabbott abbott is labours bor...,@funksoulHulk,Chris Noble,United Kingdom,North East,Middlesbrough,NaN,NaN,Twitter,41.0,M,17171.0,322.0,565.0,"(0.0, 0.0)"
17,870067031005179905,31/05/2017 23:58,http://twitter.com/MsJoNeary/status/8700670310...,stuh lachlanmoir hackneyabbott amberruddhr yes...,@MsJoNeary,Joanna Neary,United Kingdom,NaN,NaN,NaN,NaN,Twitter,51.0,F,5192.0,1944.0,630.0,"(-0.125, 0.375)"
18,870067074374266884,31/05/2017 23:58,http://twitter.com/A_mkn_/status/8700670743742...,rt hackneyabbott theresamay claims shes so tou...,@A_mkn_,AM,NaN,NaN,NaN,NaN,NaN,Twitter,28.0,NaN,10799.0,159.0,225.0,"(0.3055555555555556, 0.5666666666666667)"
19,870066916689358848,31/05/2017 23:58,http://twitter.com/longlostlohan/status/870066...,rt hackneyabbott amberruddhr heard you were as...,@longlostlohan,full metal grandma,Malaysia,NaN,NaN,NaN,NaN,Twitter,28.0,NaN,58011.0,729.0,146.0,"(0.0, 0.18888888888888888)"
20,870067039930593284,31/05/2017 23:58,http://twitter.com/chunks_1892/status/87006703...,rt hackneyabbott amberruddhr heard you were as...,@chunks_1892,Richie McIvor,United Kingdom,North West,Liverpool,NaN,NaN,Twitter,26.0,M,3586.0,398.0,799.0,"(0.0, 0.18888888888888888)"
21,870066928559296513,31/05/2017 23:58,http://twitter.com/__lilyvictoria/status/87006...,rt hackneyabbott in tough brexit negotiations ...,@__lilyvictoria,lils,United Kingdom,NaN,NaN,NaN,NaN,Twitter,42.0,NaN,18808.0,884.0,1003.0,"(-0.3888888888888889, 0.8333333333333334)"
22,870067050500288512,31/05/2017 23:58,http://twitter.com/rhiannon_arian/status/87006...,rt sarahchampionmp did you notice rudd say cri...,@rhiannon_arian,Rhiannon Arian,NaN,NaN,NaN,NaN,NaN,Twitter,48.0,F,18602.0,624.0,343.0,"(-0.5, 0.5333333333333333)"
23,870066869843177472,31/05/2017 23:58,http://twitter.com/janner_geek/status/87006686...,rt hackneyabbott in tough brexit negotiations ...,@janner_geek,Chris,United Kingdom,South West,Plymouth,NaN,NaN,Twitter,38.0,M,2424.0,164.0,351.0,"(-0.3888888888888889, 0.8333333333333334)"
24,870067101742116865,31/05/2017 23:58,http://twitter.com/T_G_Heathfield/status/87006...,rt hackneyabbott amberruddhr heard you were as...,@T_G_Heathfield,Thomas Heathfield,Spain,Madrid,Madrid,NaN,NaN,Twitter,13.0,M,88.0,29.0,59.0,"(0.0, 0.18888888888888888)"
25,870067112857001985,31/05/2017 23:58,http://twitter.com/conniepaterson/status/87006...,rt joannaccherry written questions are for bac...,@conniepaterson,connie paterson,NaN,NaN,NaN,NaN,NaN,Twitter,27.0,F,6238.0,61.0,26.0,"(0.1, 0.4)"
26,870066712665784321,31/05/2017 23:57,http://twitter.com/TulipSiddiq/status/87006671...,rt lendunne i just had a conversation with tul...,@TulipSiddiq,Tulip Siddiq,United Kingdom,Greater London,London,NaN,NaN,Twitter,66.0,NaN,8947.0,34239.0,1091.0,"(0.2, 0.30000000000000004)"
27,870066756236304385,31/05/2017 23:57,http://twitter.com/louise1580/status/870066756...,paulinewoodhams hackneyabbott well thats not r...,@louise1580,Louise Gray,NaN,NaN,NaN,NaN,NaN,Twitter,40.0,F,565.0,74.0,210.0,"(0.23690476190476187, 0.7285714285714286)"
28,870066699697102848,31/05/2017 23:57,http://twitter.com/JoePoePorter/status/8700666...,rt hackneyabbott in tough brexit negotiations ...,@JoePoePorter,Joseph Sama ??,United Kingdom,NaN,NaN,NaN,NaN,Twitter,33.0,M,30679.0,886.0,523.0,"(-0.3888888888888889, 0.8333333333333334)"
29,870066816453931008,31/05/2017 23:57,http://twitter.com/thomas_adf/status/870066816...,jessphillips pretty sexist judging a man on wh...,@thomas_adf,Thomas de Freitas,United Kingdom,NaN,NaN,NaN,NaN,Twitter,48.0,M,1985.0,192.0,474.0,"(0.25, 1.0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2269970,817456021513928705,NaN,http://twitter.com/Princemezy/status/817456021...,httptwittercomprincemezystatus817456021513928705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,20.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269971,817467503978876930,NaN,http://twitter.com/NickThornber/status/8174675...,httptwittercomnickthornberstatus81746750397887...,NaN,NaN,United Kingdom,East Midlands,Leicester,NaN,NaN,Twitter,45.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269972,817410567082299392,NaN,http://twitter.com/LSanders_Star/status/817410...,httptwittercomlsandersstarstatus81741056708229...,NaN,NaN,United Kingdom,West Midlands,Birmingham,NaN,NaN,Twitter,48.0,F,NaN,NaN,NaN,"(0.0, 0.0)"
2269973,817419881532555264,NaN,http://twitter.com/SimplyVeggie/status/8174198...,httptwittercomsimplyveggiestatus81741988153255...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,42.0,F,NaN,NaN,NaN,"(0.0, 0.0)"
2269974,817280301676302336,NaN,http://twitter.com/AndrewGDavidson/status/8172...,httptwittercomandrewgdavidsonstatus81728030167...,NaN,NaN,United Kingdom,Greater London,London,NaN,NaN,Twitter,40.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269975,817509334313762817,NaN,http://twitter.com/peterhollely/status/8175093...,httptwittercompeterhollelystatus81750933431376...,NaN,NaN,United Kingdom,Greater London,London,NaN,NaN,Twitter,41.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269976,817176699481812993,NaN,http://twitter.com/billyboyRFC/status/81717669...,httptwittercombillyboyrfcstatus817176699481812993,NaN,NaN,United Kingdom,Northern Ireland,Belfast,NaN,NaN,Twitter,42.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269977,817442015680090113,NaN,http://twitter.com/godwin_nwaugo/status/817442...,httptwittercomgodwinnwaugostatus81744201568009...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,46.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269978,817311223985438720,NaN,http://twitter.com/iamths1973/status/817311223...,httptwittercomiamths1973status817311223985438720,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,50.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269979,817494230725787648,NaN,http://twitter.com/Gogofrancis/status/81749423...,httptwittercomgogofrancisstatus817494230725787648,NaN,NaN,Nigeria,Rivers,Port Harcourt,NaN,NaN,Twitter,34.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269980,817459744730480642,NaN,http://twitter.com/AP_Doramaqueen/status/81745...,httptwittercomapdoramaqueenstatus8174597447304...,NaN,NaN,United Kingdom,Greater London,London,NaN,NaN,Twitter,53.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269981,817378104305979392,NaN,http://twitter.com/markmcdsnp/status/817378104...,httptwittercommarkmcdsnpstatus817378104305979392,NaN,NaN,United Kingdom,North Eastern,Aberdeen,NaN,NaN,Twitter,64.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269982,817190780720807936,NaN,http://twitter.com/OsasSuly/status/81719078072...,httptwittercomosassulystatus817190780720807936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,18.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269983,817183165706096640,NaN,http://twitter.com/GMgbudom/status/81718316570...,httptwittercomgmgbudomstatus817183165706096640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,25.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269984,817334951184109568,NaN,http://twitter.com/shorerdloyal/status/8173349...,httptwittercomshorerdloyalstatus81733495118410...,NaN,NaN,United Kingdom,Northern Ireland,NaN,NaN,NaN,Twitter,39.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269985,817183085817188352,NaN,http://twitter.com/kamayoq/status/817183085817...,httptwittercomkamayoqstatus817183085817188352,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,25.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269986,817492736500760576,NaN,http://twitter.com/Osinachi01/status/817492736...,httptwittercomosinachi01status817492736500760576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,17.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269987,817310510655963137,NaN,http://twitter.com/CareIndustryNew/status/8173...,httptwittercomcareindustrynewstatus81731051065...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,46.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269988,817497684848349184,NaN,http://twitter.com/frackfreemps/status/8174976...,httptwittercomfrackfreempsstatus81749768484834...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,52.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269989,817360076759564288,NaN,http://twitter.com/NEWTEKWORLDNEWS/status/8173...,httptwittercomnewtekworldnewsstatus81736007675...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,NaN,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269990,817173445540794368,NaN,http://twitter.com/JohnMullenEdin/status/81717...,httptwittercomjohnmullenedinstatus817173445540...,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,41.0,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269991,817478360578322433,NaN,http://twitter.com/SecureLegal/status/81747836...,httptwittercomsecurelegalstatus817478360578322433,NaN,NaN,United Kingdom,West Midlands,Stoke,NaN,NaN,Twitter,40.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269992,817295895888797696,NaN,http://twitter.com/ADPHUK/status/8172958958887...,httptwittercomadphukstatus817295895888797696,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,50.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269993,817377467606462464,NaN,http://twitter.com/misslucyp/status/8173774676...,httptwittercommisslucypstatus817377467606462464,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,45.0,F,NaN,NaN,NaN,"(0.0, 0.0)"
2269994,817300618402533377,NaN,http://twitter.com/GMBCampaigns/status/8173006...,httptwittercomgmbcampaignsstatus81730061840253...,NaN,NaN,United Kingdom,East Midlands,NaN,NaN,NaN,Twitter,52.0,NaN,NaN,NaN,NaN,"(0.0, 0.0)"
2269995,817511521093844992,NaN,http://twitter.com/Jamielog1/status/8175115210...,httptwittercomjamielog1status817511521093844992,NaN,NaN,United Kingdom,North West,Liverpool,NaN,NaN,Twitter,31.0,F,NaN,NaN,NaN,"(0.0, 0.0)"
2269996,817312238197440513,NaN,http://twitter.com/AlisonJenner6/status/817312...,httptwittercomalisonjenner6status8173122381974...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Twitter,52.0,F,NaN,NaN,NaN,"(0.0, 0.0)"
2269997,817412051991756800,NaN,http://twitter.com/LeeMartin113/status/8174120...,httptwittercomleemartin113status81741205199175...,NaN,NaN,United Kingdom,South Western,Greenock,NaN,NaN,Twitter,NaN,M,NaN,NaN,NaN,"(0.0, 0.0)"
2269998,817460627312615424,NaN,http://twitter.com/msjanehenshaw/status/817460...,httptwittercommsjanehenshawstatus8174606273126...,NaN,NaN,United Kingdom,West Wales and the Valleys,Cardiff,NaN,NaN,Twitter,27.0,F,NaN,NaN,NaN,"(0.0, 0.0)"
2269999,817436705431154688,NaN,http://twitter.com/JGJabbour/status/8174367054...,httptwittercomjgjabbourstatus817436705431154688,NaN,NaN,United Kingdom,NaN,NaN,NaN,NaN,Twitter,36.0,M,NaN,NaN,NaN,"(0.0, 0.0)"

In [5]:
new_col_list = ['sentiment score ','subjectivity']
for n,col in enumerate(new_col_list):
    df[col] = df['sentiment'].apply(lambda location: location[n])
df=df.drop('sentiment', axis=1)

df.describe()

/Users/IzzIbrahim/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,GUID,Category,Emotion,Klout Score,Posts,Followers,Following,sentiment score,subjectivity
count,2.270000e+06,0.0,0.0,2.191607e+06,2.267654e+06,2.267654e+06,2.267654e+06,2.270000e+06,2.270000e+06
mean,8.452829e+17,NaN,NaN,4.352996e+01,3.132044e+04,2.999925e+03,1.357188e+03,7.996644e-02,3.667758e-01
std,1.677498e+16,NaN,NaN,1.188502e+01,6.039390e+04,5.358599e+04,4.608701e+03,3.071261e-01,3.332986e-01
min,8.153468e+17,NaN,NaN,1.000000e+01,1.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00
25%,8.301322e+17,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
50%,8.453790e+17,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,3.555556e-01
75%,8.601683e+17,NaN,NaN,NaN,NaN,NaN,NaN,2.172619e-01,6.000000e-01
max,8.729665e+17,NaN,NaN,9.900000e+01,7.203010e+06,3.510944e+07,7.499740e+05,1.000000e+00,1.000000e+00

# TF.IDF

In [6]:
# from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
# v = TfidfVectorizer(stop_words='english')
# y = v.fit_transform(df['Contents'])

In [ ]:
# df['tweetsVect']=list(y)
# df.head()

# Abusive Words

In [22]:
words=pd.read_excel('Abusive Words List.xlsx')
words.head()

                  Key Word
0  attention seeking whore
1      little fucking cunt
2           feminist bitch
3           feminist whore
4            feminist cunt

In [23]:
words['Key Word']=words['Key Word'].apply(lambda x: x if type(x)!=str else x.lower()) # lower case
words['Key Word']=words['Key Word'].apply(lambda x: ''.join([i for i in x
                                                                  if i not in string.punctuation]))

In [24]:
words.head()

                  Key Word
0  attention seeking whore
1      little fucking cunt
2           feminist bitch
3           feminist whore
4            feminist cunt

In [36]:
#def countabuse(text):
  #  return sum(keyword in text.split(' ') for keyword in words['Key Wordtext])


#df['AbuseCount'] = df['Contents'].map(countabuse)

In [44]:
import re

def is_present(text, key_words):
    non_alphanum='[^A-Za-z0-9]'
    count=0
    for phrase in key_words:
        r= re.compile(non_alphanum + phrase + non_alphanum)
        match=re.search(r, text)
        if match:
            count +=1
    return count

In [ ]:
df['AbuseCount'] = df['Contents'].map(lambda x: is_present(x, words['Key Word']))

In [38]:
df.describe()

/Users/IzzIbrahim/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,GUID,Category,Emotion,Klout Score,Posts,Followers,Following,sentiment score,subjectivity,Count A,AbuseCount
count,2.270000e+06,0.0,0.0,2.191607e+06,2.267654e+06,2.267654e+06,2.267654e+06,2.270000e+06,2.270000e+06,2270000.0,2.270000e+06
mean,8.452829e+17,NaN,NaN,4.352996e+01,3.132044e+04,2.999925e+03,1.357188e+03,7.996644e-02,3.667758e-01,0.0,2.145771e-02
std,1.677498e+16,NaN,NaN,1.188502e+01,6.039390e+04,5.358599e+04,4.608701e+03,3.071261e-01,3.332986e-01,0.0,1.487271e-01
min,8.153468e+17,NaN,NaN,1.000000e+01,1.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.0,0.000000e+00
25%,8.301322e+17,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.0,0.000000e+00
50%,8.453790e+17,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,3.555556e-01,0.0,0.000000e+00
75%,8.601683e+17,NaN,NaN,NaN,NaN,NaN,NaN,2.172619e-01,6.000000e-01,0.0,0.000000e+00
max,8.729665e+17,NaN,NaN,9.900000e+01,7.203010e+06,3.510944e+07,7.499740e+05,1.000000e+00,1.000000e+00,0.0,4.000000e+00

In [33]:
abusiveDF=df[(df['AbuseCount']!=0)]

In [35]:
abusiveDF.to_excel('AbusiveT.xls')

In [42]:
df['']